#!/bin/bash

set -euo pipefail

# Creates a tgz but in the directory 'package' which we need to remove
f="$(npm pack)"

# Let's strip the `package` dir by extracting into pkg
rm -rf pkg && mkdir -p pkg && tar -zxf "$f" --strip 1 -C pkg

# Overwrite the original tar.gz, with a prefix-less version
(
  cd pkg && tar -czf "../$f" .
)

# Place the final file in the `pkg` dir
rm -rf pkg && mkdir pkg && mv "$f" pkg

echo "🙌 Created pkg/$f ready for release"

open pkg