#!/bin/bash

# We want to distribute a .tar.gz file with our GitHub releases that can be used
# in the HomeBrew recipes. We use `npm pack` to create one that matches what's
# distributed on npm, but we need to remove the `package/` directory prefix that
# it uses.

set -euo pipefail

# Creates a tgz but in the directory 'package' which we need to remove
f="$(npm pack)"

# Let's strip the `package` dir by extracting into pkg
rm -rf pkg && mkdir -p pkg && tar -zxf "$f" --strip 1 -C pkg

# Overwrite the original tar.gz, with a prefix-less version
(
  cd pkg && tar -czf "../$f" .
)

# Place the final file in the `pkg` dir
rm -rf pkg && mkdir pkg && mv "$f" pkg/bksr.tgz

echo "🙌 Created pkg/$f ready for release"

open pkg